# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Default
  variables:
    System.Debug: true
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: Application security testing@2023
    displayName: Application security testing
    inputs:
      projectName: CxTest
      enableSastScan: false
      CheckmarxService: 61c5f2c3-f703-4a9f-90c5-84da95eccf9c
      fullTeamName: CxServer
      incScan: false
      fullScansScheduled: false
      enableDependencyScan: true
      dependencyServerURL: 246a819e-6c32-4bb7-bfa4-a8f1b33f4b1f
      manifestPattern: test
      fingerprintPattern: test
      scaTeam: CxServer
...