parameters:

- name: cxService

  type: string

  default: SAST-Bug

 

variables:

- name: debug

  value: true 

pool:

#    name: Default

     vmImage: 'macos latest'

  

steps:

- bash: echo '-s $(Build.SourcesDirectory) -n newSCA5501 -r $(Agent.BuildDirectory)'    

- task: Checkmarx-Prerelease.cxsast.cx-scan-task.Application security testing@2023

  displayName: 'Application security testing'

  inputs:

      projectName: newSCA5501

      syncMode: true

      enableProxy: false

      enableSastScan: false

      enableDependencyScan: true

      dependencyServerURL: scaNewConnection1

      dependencyAccessControlURL: 'https://platform.checkmarx.net'

      dependencyWebAppURL: 'https://sca.checkmarx.net'

      includeSource: false

      dependencyFolderExclusion: 'cvs,.svn,.hg,.git,.bzr,bin,obj,backup,.idea,node_modules'

      dependencyTenant: plugins

      scaVulnerabilityThreshold: false
 
      isEnableScaResolver: true

      scaResolverAddParameters: '-s $(Build.SourcesDirectory) -n newSCA5501 -r $(Agent.BuildDirectory)'

      scaHigh: ' '

      scaMedium: ' '

      scaLow: ' '

      scaTeam: 'CxServer/'
